name: class_switch_annotation
description: >-
  Package containing the annotations used by the `class_switch` package to specify which classes to generate dispatchers
  for.
version: 0.0.1
homepage: https://github.com/nigel-gott/class_switch
author: Nigel Gott <nigel.gott@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
