# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyze:
      - dartanalyzer
      - dartfmt
  - unit_test:
      - test

cache:
  directories:
    - .dart_tool/build