name: class_switch_generator
description: >-
  Generates abstract dispatcher classes with handle methods for all sub classes of an annotated class.
version: 0.0.1-dev.0
homepage: https://github.com/nigel-gott/class_switch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  optional: ^6.0.0-nullsafety.0
  class_switch: ^0.0.1-dev.0
  analyzer: ^1.3.0
  meta: ^1.3.0
  generic_reader: ^0.2.2

dev_dependencies:
  pedantic: ^1.11.0
  source_gen_test: ^1.0.0
  test: ^1.16.5
  build_runner: ^1.12.2
  build_test: ^2.0.0
