name: class_switch_generator
description: >-
  `class_switch_generator` lets you switch over all the sub-classes of a class instance
   or all possible combinations of sub-classes for multiple base class instances.
version: 0.0.1-dev.2
homepage: https://github.com/nigel-gott/class_switch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^5.3.0
  build: ^2.0.0
  class_switch: ^0.0.1-dev.2
  meta: ^1.8.0
  optional: ^6.1.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.5
  lint: ^2.0.0
  source_gen_test: ^1.0.4
  test: ^1.22.1

#dependency_overrides:
# class_switch:
#   path: ../class_switch
