name: dispatchable_example
homepage: https://github.com/nigel-gott/dispatchable
author: Nigel Gott <nigel.gott@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  dispatchable_generator:
    path: ../dispatchable_generator/
  dispatchable_annotation:
    path: ../dispatchable_annotation/

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.4
  build_runner: ^1.6.1
