# Created with package:mono_repo v2.1.0
language: dart

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: dev; PKGS: class_switch, class_switch_annotation, class_switch_client_test, class_switch_example; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings --fatal-infos .`]"
      dart: dev
      env: PKGS="class_switch class_switch_annotation class_switch_client_test class_switch_example"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
    - stage: analyzer_and_format
      name: "SDK: 2.2.2; PKGS: class_switch, class_switch_client_test; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: "2.2.2"
      env: PKGS="class_switch class_switch_client_test"
      script: ./tool/travis.sh dartanalyzer_1
    - stage: analyzer_and_format
      name: "SDK: 2.2.2; PKGS: class_switch_annotation, class_switch_example; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings .`]"
      dart: "2.2.2"
      env: PKGS="class_switch_annotation class_switch_example"
      script: ./tool/travis.sh dartfmt dartanalyzer_1
    - stage: unit_test
      name: "SDK: 2.2.2; PKGS: class_switch, class_switch, class_switch_client_test; TASKS: `pub run test`"
      dart: "2.2.2"
      env: PKGS="class_switch class_switch class_switch_client_test"
      script: ./tool/travis.sh command_0
    - stage: unit_test
      name: "SDK: dev; PKGS: class_switch, class_switch, class_switch_client_test; TASKS: `pub run test`"
      dart: dev
      env: PKGS="class_switch class_switch class_switch_client_test"
      script: ./tool/travis.sh command_0
    - stage: unit_test
      name: "SDK: 2.2.2; PKG: class_switch_client_test; TASKS: `pub run build_runner test --delete-conflicting-outputs`"
      dart: "2.2.2"
      env: PKGS="class_switch_client_test"
      script: ./tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: dev; PKG: class_switch_client_test; TASKS: `pub run build_runner test --delete-conflicting-outputs`"
      dart: dev
      env: PKGS="class_switch_client_test"
      script: ./tool/travis.sh command_1

stages:
  - analyzer_and_format
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - class_switch/.dart_tool/build
    - class_switch_client_test/.dart_tool/build
