# See https://github.com/dart-lang/mono_repo for details
sdk:
  - stable

stages:
  - analyze:
      - group:
        - command: pub run build_runner build --delete-conflicting-outputs
        - format
        - analyze
  - unit_test:
      - command: pub run build_runner test --delete-conflicting-outputs

cache:
  directories:
    - .dart_tool/build
