# See https://github.com/dart-lang/mono_repo for details
stages:
  - analyzer_and_format:
      - group:
          - command: pub run build_runner build --delete-conflicting-outputs
          - dartfmt
          - dartanalyzer: --fatal-warnings --fatal-infos .
        dart: [stable]
