# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyze:
      - command: pub run build_runner build --delete-conflicting-outputs
      - dartfmt
      - dartanalyzer

cache:
  directories:
    - .dart_tool/build
