name: dispatchable_project_example
homepage: https://github.com/nigel-gott/dispatchable
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dispatchable: ^0.0.1-dev.2

dev_dependencies:
  dispatchable_generator: ^0.0.1-dev.2
  pedantic: ^1.11.0
  test: ^1.16.5
  build_runner: ^1.12.2
