targets:
  $default:
    builders:
      class_switch:
        enabled: true
builders:
  class_switch:
    import: "package:class_switch/builder.dart"
    builder_factories: ["typeHandler"]
    build_extensions: {".dart": [".class_switch.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]