# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.3.0
  - stable

stages:
  - analyzer_and_format:
      - group:
          - dartfmt
          - dartanalyzer: --fatal-warnings --fatal-infos .
        dart: [stable]
  - unit_test:
      - group:
          - command: pub run test
        dart: [stable]

cache:
  directories:
    - .dart_tool/build