name: class_switch
description: >-
  class_switch lets you you switch over all the sub-classes of a class instance
  or over multiple different classes at once. Pairs with class_switch_generator
  which does the actual code generation to enable class switching.
version: 0.0.1-dev.1
homepage: https://github.com/nigel-gott/class_switch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
