name: class_switch
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: nigel <nigel.gott@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  build: ^1.1.4
  source_gen: ^0.9.4+2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.4
  build_runner: ^1.6.1
  build_test: ^0.10.8
