name: class_switch
description: >-
  Package containing the annotations used by the `class_switch_generator` package to
  specify which classes to generate dispatchers for.
version: 0.0.1-dev.0
homepage: https://github.com/nigel-gott/class_switch

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
