name: class_switch
description: >-
  `class_switch_generator` lets you switch over all the sub-classes of a class instance
   or all possible combinations of sub-classes for multiple base class instances.
version: 0.0.1-dev.2
homepage: https://github.com/nigel-gott/class_switch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
