targets:
  $default:
    builders:
      dispatchable:
        enabled: true
builders:
  dispatchable:
    import: "package:dispatchable_generator/builder.dart"
    builder_factories: ["dispatchable"]
    build_extensions: {".dart": [".dispatchable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]