name: dispatchable_generator
description: >-
  Generates dispatchers which take handlers for all sub classes of an annotated class, allowing you to have type safety
  guarantees that all possible sub classes have been considered by a given dispatcher.
version: 0.0.1
homepage: https://github.com/nigel-gott/dispatchable
author: Nigel Gott <nigel.gott@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  build: ^1.1.4
  source_gen: ^0.9.4+2
  optional: ^3.1.0
  dispatchable_annotation:
    git:
      url: git@github.com:nigel-gott/dispatchable.git
      path: dispatchable_annotation

dev_dependencies:
  pedantic: ^1.8.0
  source_gen_test: ^0.1.0+5
  test: ^1.6.4
  build_runner: ^1.6.1
  build_test: ^0.10.8
