# See https://github.com/dart-lang/mono_repo for details
sdk:
  - stable

stages:
  - analyze:
      - group:
        - command: pub run build_runner build --delete-conflicting-outputs
        - format
        - analyze

cache:
  directories:
    - .dart_tool/build
