name: class_switch_project_example
homepage: https://github.com/nigel-gott/class_switch
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  class_switch: ^0.0.1-dev.3

dev_dependencies:
  build_runner: ^2.3.3
  class_switch_generator: ^0.0.1-dev.3
  lint: ^2.0.0
  test: ^1.22.1

#dependency_overrides:
#  class_switch_generator:
#    path: ../class_switch_generator
