name: class_switch_example
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: nigel <nigel.gott@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  class_switch:
    path: ../class_switch/

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.4
  build_runner: ^1.6.1
