name: class_switch_example
homepage: https://github.com/nigel-gott/class_switch
author: Nigel Gott <nigel.gott@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  class_switch:
    path: ../class_switch/
  class_switch_annotation:
    path: ../class_switch_annotation/

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.4
  build_runner: ^1.6.1
